### PR TITLE
[J11] ACD-36 Added support for non-OSGi VM and sanitize for Java 11.

### LINKED ISSUE #36: Add support for non-OSGi VM
### Description
Add support for VM that are not OSGi containers where bundles don't exist. So protection domains would need to be reported via their code source location.

#### Expected behavior:
Be able to attach the AC debugger to a JVM that is not an OSGi container.

#### Actual behavior:
Currently fails.

#### Reproduces how often:
100%

### Version
1.5

### PR DESCRIPTION
**Pull request by paouelle**
### Description of the Change
This PR adds support for non-OSGi VM where it reports the domain codesource location where the failure is detected. It also sanitized its compatibility with Java 11 VMs.

It replace bundles with domains wherever it was more generic.
It adds class or instance location in debug output to better troubleshoot cases where the code is in a base class of a given object.
It adds system property expansion for domain locations and file permission names and made it configurable. It does so when both using or not using the backdoor.
It fixes when using backdoor to get bundle to rely on the result even if null.
It fixes printout.

### Benefits
The debugger can now be used when debugging non-OSGi VM and provides more debug information when needed.

### Verification Process
- Attempt to attach to DDF and verify debug output for known security exceptions.
- Attempt to attach to Solr and verify debug output

### Applicable Issues
Fixes: #36

### CODE REVIEW

File: common/src/main/java/org/codice/acdebugger/common/Resources.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+import java.io.InputStream;
+import java.io.InputStreamReader;
+import java.io.Reader;
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+import java.util.function.Function;
+
+/** Utility classes for managing resources. */
+public class Resources {
```
Comment (paouelle) [inline common/src/main/java/org/codice/acdebugger/common/Resources.java:28]: ℹ️ I didn't want to embed Guava

File: debugger/src/main/java/org/codice/acdebugger/api/ReflectionUtil.java [hunk 2]
```diff
@@ -341,10 +415,7 @@ public Method findMethod(ReferenceType type, String name, String signature) {
     if (obj == null) {
       return null;
     }
-    final ReferenceType type =
-        (obj instanceof ClassObjectReference)
-            ? ((ClassObjectReference) obj).reflectedType()
-            : obj.referenceType();
+    final ReferenceType type = obj.referenceType();
```
Comment (paouelle) [inline debugger/src/main/java/org/codice/acdebugger/api/ReflectionUtil.java:419]: ℹ️ The original code was to handle static method calls which are now handled separately with `invokeStatic()`. It also created issues when actually trying to invoke methods on the class `Class`.

File: debugger/src/main/java/org/codice/acdebugger/api/ReflectionUtil.java [hunk 3]
```diff
@@ -282,10 +282,7 @@ public Method findMethod(ReferenceType type, String name, String signature) {
...
```
Comment (paouelle) [inline debugger/src/main/java/org/codice/acdebugger/api/ReflectionUtil.java:286]: ℹ️ The original code was to handle static fields which are now handled separately with `getStatic()`. It also created issues when actually trying to access static field of the class `Class`.

File: debugger/src/main/java/org/codice/acdebugger/breakpoints/SecurityCheckInformation.java [hunk 4]
```diff
@@ -168,30 +170,32 @@ private SecurityCheckInformation(
...
     this.local_i = local_i;
-    this.currentDomain = context.get(local_i);
-    this.currentBundle = debug.bundles().get(currentDomain);
+    this.currentDomainValue = context.get(local_i);
+    this.currentDomain = debug.locations().get(currentDomainValue);
     this.domains = new ArrayList<>(context.size());
     this.permission = permission;
     this.privilegedDomains = new HashSet<>(context.size() * 3 / 2);
     for (int i = 0; i < context.size(); i++) {
-      if (i == local_i) { // we know we don't have privileges since we failed here
```
Comment (paouelle) [inline debugger/src/main/java/org/codice/acdebugger/breakpoints/SecurityCheckInformation.java:177]: ℹ️ This was improperly skipping the current domain and it wasn't being added to the context. So it got moved a little bit further down.

File: debugger/src/main/java/org/codice/acdebugger/breakpoints/SecurityCheckInformation.java [hunk 5]
```diff
@@ -570,7 +574,7 @@ private void analyzeDoPrivilegedBlocks(Debug debug) {
   }
 
   @SuppressWarnings("squid:S106" /* this is a console application */)
-  private void dumpPermission() {
+  protected void dumpPermission() {
```
Comment (paouelle) [inline debugger/src/main/java/org/codice/acdebugger/breakpoints/SecurityCheckInformation.java]: ❗️ Will move back to private

File: debugger/src/main/java/org/codice/acdebugger/breakpoints/SecurityCheckInformation.java [hunk 6]
```diff
@@ -583,13 +587,20 @@ private void dumpPermission() {
   }
 
   @SuppressWarnings("squid:S106" /* this is a console application */)
-  private void dumpHowToFix() {
-    if (!grantedBundles.isEmpty()) {
-      final String bs = (grantedBundles.size() == 1) ? "" : "s";
+  protected void dumpHowToFix(boolean osgi) {
```
Comment (paouelle) [inline debugger/src/main/java/org/codice/acdebugger/breakpoints/SecurityCheckInformation.java]: ❗️ Will move back to private

**Comment by paouelle** [comment]
build now

**Comment by oconnormi** [comment]
Build Now

**Comment by paouelle** [comment]
build now

File: debugger/src/main/java/org/codice/acdebugger/api/SecuritySolution.java [hunk 7]
```diff
@@ -88,44 +88,68 @@ protected SecuritySolution(SecuritySolution solution) {
...
-      permissionInfos
-          .stream()
-          .sorted()
-          .forEach(
-              p ->
-                  System.out.println(
-                      ACDebugger.PREFIX + prefix + "            permission " + p + ";"));
-      System.out.println(ACDebugger.PREFIX + prefix + "        }");
+    if (!grantedDomains.isEmpty()) {
+      if (osgi) {
```
Comment (coyotesqrl) [inline debugger/src/main/java/org/codice/acdebugger/api/SecuritySolution.java:112]: ✏️ Probably worth breaking the osgi/non-osgi blocks out to their own private methods.

**Comment by paouelle** [comment]
build now

File: debugger/src/main/java/org/codice/acdebugger/impl/DebugContext.java [hunk 8]
```diff
@@ -62,68 +66,77 @@ public Backdoor getBackdoor() {
   }
 
   /**
-   * Checks if a bundle has or was temporarily granted a given permission.
+   * Accesses system properties util functionnality.
```
Comment (coyotesqrl) [inline debugger/src/main/java/org/codice/acdebugger/impl/DebugContext.java]: ✏️ "functionality"

**Review by coyotesqrl — APPROVED** [review]

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now - socket exception trying to run sonarQube

**Comment by paouelle** [comment]
build now
